# Dockerfile
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN yes | unminimize

# Instalacion de dependencias comunes
RUN apt-get update && apt-get install -y \
    man-db manpages manpages-dev manpages-posix less \
    unzip \
    snmp snmp-mibs-downloader \
    snmpd \
    iputils-ping \
    net-tools \
    iproute2 \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Creación del directorio de trabajo
WORKDIR /gpx

# Copia de los archivos del proyecto
COPY gp2.zip /gpx/gp2.zip
COPY ./agent/snmp-agent-setup.sh /gpx/snmp-agent-setup.sh

# Otorga los permisos de ejecución de los scripts
RUN chmod +x /gpx/snmp-agent-setup.sh
RUN /gpx/snmp-agent-setup.sh install

# Deja el contenedor en modo interactivo
CMD ["/gpx/snmp-agent-setup.sh", "start"]
